services:
  - name: bitcoin
    image: nicolasdorier/docker-bitcoin:0.16.3
    args:
      - bitcoind
      - -testnet
    resources:
      cpus: 1
      memory: 2 GB
      storage: 5 GiB
task-runners:
  - name: testnet-expiration
    script:
      inline: sleep 600
tests:
  - name: simple-bitcoin-exercise
    description: join the bitcoin testnet and validate some blocks
    system:
      - name: bitcoin-node-testnet
        type: bitcoin
        count: 4
    phases:
      - name: basic
        tasks:
          - type: testnet-expiration
            timeout: 11 m
