services:
  - name: geth
    image: ethereum/client-go
    args:
      - --dev
      - --logfile=/var/log/geth/geth.log
    volumes:
      - path: /var/log/geth
        name: geth-logs
    resources:
      cpus: 2
      memory: 4 GB
      storage: 100 GiB
  - name: nginx
    image: "nginx:latest"
    resources:
      cpus: 2
      memory: 4 GB
      storage: 100 GiB
sidecars:
  - name: "yes"
    sidecar-to:
      - nginx
    script:
      inline: "yes"
    resources:
      cpus: 1
      memory: 512 MB
      storage: 8 GiB
task-runners:
  - name: geth-transactions
    image: ubuntu:latest
    script:
      inline: echo hello
tests:
  - name: exercise-geth
    description: run a geth testnet and execute some simple transactions
    system:
      - type: geth
        count: 2
    phases:
      - name: baseline-tps
        tasks:
          - type: geth-transactions
            timeout: 5 m
      - name: tps-with-latency
        system:
          - type: geth
            name: geth
            resources:
              networks:
                - name: default
                  latency: 100 ms
        tasks:
          - type: geth-transactions
            timeout: 5 m
      - name: nginx-deploy
        system:
          - type: nginx
            name: nginx
            count: 10
            resources:
              networks:
                - name: foobar
                  latency: 100 ms
                - name: barfoo
                  latency: 100 ms
        tasks:
          - type: geth-transactions
            timeout: 5 m