services:
  - name: besu
    image: "hyperledger/besu:develop"
    script:
      inline: cp /staticpeers/static-nodes.json /var/lib/besu/static-nodes.json && besu --genesis-file=/tmp/genesis.json --miner-enabled --discovery-enabled=false --data-path=/var/lib/besu
    input-files:
      - source-path: ./genesis.json
        destination-path: /tmp/genesis.json
    volumes:
      - path: /staticpeers/
        name: staticpeers
        scope: singleton
    resources:
      cpus: 2
      memory: 3 GB
      storage: 5 GiB
task-runners:
  - name: wait
    script:
      inline: sleep 1800
  - name: static-peers # generate static peers
    image: "gcr.io/whiteblock/helpers/besu/staticpeers"
    volumes:
      - path: /staticpeers/
        name: staticpeers
        scope: singleton
    script:
      inline: ./besuStaticPeers generate -a '[{"privateKey":"317f5a5a1e73f10202e9d601834c387a8d6769aab87afe9bfba318e309224e42", "publicKey":"9de23f4bcd0354611424e8787e0ad26c491d2f6e76101c16ddfd311fd1be71bf4675cbf252559617e220224af048e194e881c8c6165040d73c7d23fcb279b750", "address":"0xb8172dc7230f3b84787331a976218d57735b65bb"},{"privateKey":"cfee8b81a9966d58e2fe5e8c6914c7b309ca795a36551e9765d62a65c3cea56d", "publicKey":"480e689b2638fec9b4353c2ede5d1af83138cca3023baf72f1b6ec792fe5396cbe91177d50ad8cae8eaa0369e93c78575990227048358537e92eb54208fb074d", "address":"0xc7413a023619b09b8749598750236100badb07f7"},{"privateKey":"5d07b874ec190c444ed1a39a6104a1eaafab1e5837c259f520c3ae2e287c857d", "publicKey":"06bc1cae6689171185c7875bae0f3d7cc2556f4422944c986fe04b32864775c7bd3323f1b8020ffa4d4192ae90aa35fc3b974942145c7b718bf1f1eca360b51", "address":"0x7244c095104cc570f3e25549ee717cf0a961d889"}]' --ip '["'$BESU_SERVICE0_BESU_NETWORK'", "'$BESU_SERVICE1_BESU_NETWORK'", "'$BESU_SERVICE2_BESU_NETWORK'"]' >> /staticpeers/static-nodes.json
tests:
  - name: baseline
    description: run a simple hyperledger besu testnet consisting of 3 besu nodes
    phases:
      - name: genesis
        tasks:
          - type: static-peers
      - name: spin-up-nodes
        system:
          - name: besu
            type: besu
            count: 3
            resources:
              networks:
                - name: besu-network
      - name: wait
        tasks:
          - type: wait
            timeout: 1800 s