services:
  - name: eth1-mock-rpc
    image: gcr.io/whiteblock/eth1-mock-rpc:latest
    args:
      - --unencrypted-keys-dir=/keys
      - --genesis-deposits 64
      - --prompt-for-deposits=false
    input-files:
      - source-path: ./keystore/keys.json
        destination-path: /keys/keys.json
tests:
  - name: simple-prysm-exercise
    description: run a prysm testnet and validate some blocks
    wait-for: 10m
    system:
      - name: eth1-mock-rpc
        type: eth1-mock-rpc
        count: 1
