services:
  # see: https://github.com/prysmaticlabs/eth1-mock-rpc
  - name: eth1
    image: gcr.io/whiteblock/eth1-mock-rpc:latest
    script:
      inline: >
        /usr/local/bin/eth1-mock-rpc
        --unencrypted-keys-dir=/keys
        --genesis-deposits 64
        --prompt-for-deposits=false
        --host=0.0.0.0
    input-files:
      - source-path: ./keystore/keys.json
        destination-path: /keys/keys.json
  - name: beacon-chain
    image: gcr.io/whiteblock/prysm/beacon:latest
    script:
      inline: >
        /usr/local/bin/beacon-chain
        --http-web3provider http://${ETH1_SERVICE0_PRYSM_NETWORK}:7777
        --web3provider ws://${ETH1_SERVICE0_PRYSM_NETWORK}:7778
        --force-clear-db
        --minimal-config
        --custom-genesis-delay 12
        --datadir /tmp/beacondata
        --contract-deployment-block=2000
        --min-sync-peers=0
        --verbosity debug
        --bootstrap-node=
    resources:
      cpus: 2
      memory: 4 GB
  - name: validator
    image: gcr.io/whiteblock/prysm/validator:latest
    script:
      inline: >
        /usr/local/bin/validator
        --password 123456
        --unencrypted-keys=/keys/keys.json
        --minimal-config
        --beacon-rpc-provider=${BEACON_CHAIN_SERVICE0_PRYSM_NETWORK}:4000
    input-files:
      - source-path: ./keystore/keys.json
        destination-path: /keys/keys.json
tests:
  - name: simple-prysm-exercise
    description: run a prysm testnet and validate some blocks
    phases:
      - name: start-mock-eth1-chain
        duration: 10 s
        system:
          - type: eth1
            resources:
              networks:
                - name: prysm-network
      - name: start-beacon-chain
        duration: 10 s
        system:
          - type: beacon-chain
            resources:
              networks:
                - name: prysm-network
      - name: start-validator
        duration: 10 m
        system:
          - type: validator
            resources:
              networks:
                - name: prysm-network
